# -*- coding: utf-8 -*-
"""
Created on Sun Sep 22 13:35:20 2019

@author: jchlu
"""

language: python
python:
 - "3.5"
instal:
  - pip install pylint
  - pip install coverage
# command to run tests
script:
 - python -m unittest TestTriangle